# Drivetrain
RIGHT_FRONT_ID = 1
RIGHT_BACK_ID = 2
LEFT_FRONT_ID = 3
LEFT_BACK_ID = 4
RIGHT_ENCODER_A = 0
RIGHT_ENCODER_B = 1
LEFT_ENCODER_A = 2
LEFT_ENCODER_B = 3

# Algae Intake
INTAKE_MOTION_ID = 50
INTAKE_ROTATION_ID = 52
PID_INTAKE = (0.02, 0.01, 0)

# Climber
CLIMBER_ID = 12

# Coral Intake
CORAL_INTAKE_ID = 9

# Joysticks
DUALSHOCK4_ID = 0
XBOX_360_CONTROLLER_ID = 1